:- dynamic pergunta_missao/6.
% botar senha
% 
pergunta_missao('M1_Q5', 0, 'Qual é uma das principais desvantagens de usar uma linguagem de programação de baixo nível segundo o documento?', 'Tem pouca portabilidade.', ['É difícil de traduzir para linguagem de máquina.', 'Tem pouca portabilidade.', 'Consome menos recursos do sistema.', 'É mais simples de programar.', 'É a mais eficiente em termos de tempo.'], nao_acertada).
pergunta_missao('M1_Q11', 0, 'Qual linguagem foi fortemente inspirada em Algol e se tornou a principal para ensino de programação por sua simplicidade e suporte a programação estruturada?', 'Pascal', ['Pascal', 'C', 'Simula', 'Fortran', 'Lisp'], nao_acertada).
pergunta_missao('M1_Q12', 0, 'Qual linguagem projetada para sistemas de informação comerciais é descrita como verborrágica e ainda hoje é ativa?', 'Cobol', ['Java', 'Pascal', 'Cobol', 'Fortran', 'Python'], nao_acertada).
pergunta_missao('M1_Q13', 0, 'Qual linguagem de grande importância histórica foi utilizada para reimplementar o sistema operacional Unix?', 'C', ['C', 'Java', 'Python', 'Fortran', 'Lisp'], nao_acertada).
pergunta_missao('M1_Q14', 0, 'A que estilo de programação a linguagem Lisp de 1958 é precursora?', 'Programação funcional', ['Programação orientada a objetos', 'Programação funcional', 'Programação imperativa', 'Programação estruturada', 'Programação lógica'], nao_acertada).
pergunta_missao('M1_Q15', 0, 'O que a linguagem Algol-60 introduziu para melhorar a legibilidade e o tempo de desenvolvimento de programas?', 'O uso de blocos delimitados de código e escopo.', ['O uso de desvios incondicionais.', 'O uso de linguagens de baixo nível.', 'O uso de blocos delimitados de código e escopo.', 'A introdução da programação puramente orientada a objetos.', 'A ênfase na computação numérica.'], nao_acertada).
pergunta_missao('M1_Q16', 0, 'Qual é o significado da sigla COBOL?', 'Common Business Oriented Language', ['Common Object-Based Online Language', 'Common Business Oriented Language', 'Common Business and Office Language', 'Computer Business Oriented Language', 'Common Block-Oriented Language'], nao_acertada).
pergunta_missao('M1_Q17', 0, 'A qual das seguintes LP o documento se refere como \'Linguagem de Programação em Lógica\'?', 'Prolog', ['Lisp', 'Java', 'Python', 'Prolog', 'Smalltalk'], nao_acertada).
pergunta_missao('M1_Q18', 0, 'Qual das seguintes características de uma LP está relacionada à execução em um tempo aceitável para os propósitos de uso da linguagem?', 'Eficiência', ['Eficiência', 'Simplicidade', 'Universalidade', 'Expressividade', 'Implementável'], nao_acertada).
pergunta_missao('M1_Q19', 0, 'Segundo o documento, até os anos 50, quais eram os principais usos dos computadores?', 'Cálculos numéricos.', ['Aplicações de IA.', 'Sistemas de informação comerciais.', 'Cálculos numéricos.', 'Edição de texto.', 'Jogos.'], nao_acertada).
pergunta_missao('M1_Q20', 0, 'Qual das opções abaixo não é uma das características desejáveis em uma LP conforme listado no slide \'Características\' e \'Simplicidade\'?', 'Maior poder expressivo que dificulta o aprendizado.', ['Expressividade.', 'Simplicidade.', 'Suporte a abstração.', 'Implementável.', 'Maior poder expressivo que dificulta o aprendizado.'], nao_acertada).
pergunta_missao('M1_Q1', 0, 'Qual das seguintes não é uma característica de uma linguagem de programação conforme definido no documento?', 'Portabilidade', ['Expressividade', 'Portabilidade', 'Universalidade', 'Simplicidade', 'Implementável'], acertada).
pergunta_missao('M1_Q2', 0, 'O que a característica de \'Universalidade\' de uma linguagem de programação implica?', 'Que ela pode resolver qualquer problema que um computador seja capaz de resolver.', ['Que ela deve ser fácil de aprender.', 'Que ela pode resolver apenas problemas matemáticos.', 'Que ela pode resolver qualquer problema que um computador seja capaz de resolver.', 'Que ela deve ser usada por todos os programadores.', 'Que ela só pode ser usada em máquinas de alto desempenho.'], acertada).
pergunta_missao('M1_Q3', 0, 'De acordo com o documento, qual a principal diferença entre uma linguagem de programação e uma linguagem de consulta a banco de dados (query language)?', 'A linguagem de programação precisa dar suporte a recursão, iteração ou desvios.', ['A linguagem de programação precisa dar suporte a recursão, iteração ou desvios.', 'A linguagem de programação é sempre mais antiga.', 'A linguagem de programação é de alto nível.', 'A linguagem de consulta é mais popular.', 'A linguagem de programação é usada apenas para fins comerciais.'], acertada).
pergunta_missao('M1_Q4', 0, 'O que é uma linguagem de programação de baixo nível de acordo com o texto?', 'Uma linguagem com instruções que refletem de forma mais direta as operações em nível de máquina.', ['Uma linguagem com instruções que refletem de forma mais direta as operações em nível de máquina.', 'Uma linguagem com sintaxe complexa e difícil de usar.', 'Uma linguagem com alta portabilidade.', 'Uma linguagem que é mais lenta e consome mais recursos.', 'Uma linguagem projetada para aplicações de IA.'], acertada).
pergunta_missao('M1_Q6', 0, 'Qual linguagem de programação é citada como exemplo de uma LP de baixo nível?', 'Assembly', ['Python', 'Java', 'C++', 'Assembly', 'Pascal'], acertada).
pergunta_missao('M1_Q7', 0, 'Qual das seguintes linguagens é descrita como sendo a primeira a introduzir conceitos de orientação a objetos (OO) como classe e herança?', 'Simula', ['Pascal', 'Fortran', 'C', 'Simula', 'Lisp'], acertada).
pergunta_missao('M1_Q8', 0, 'Qual LP desenvolvida pela IBM na década de 1950 foi voltada para computação numérica e científica e introduziu o conceito de arrays e procedimentos com parâmetros?', 'Fortran', ['Algol-60', 'Pascal', 'C', 'Simula', 'Fortran'], acertada).
pergunta_missao('M1_Q9', 0, 'Qual LP descrita no documento como a primeira puramente orientada a objetos e dinamicamente tipada e oferece suporte a reflexão?', 'Smalltalk', ['Java', 'C', 'C++', 'Smalltalk', 'Simula'], acertada).
pergunta_missao('M1_Q10', 0, 'O documento menciona que a programação estruturada começou a ser introduzida com qual linguagem?', 'Algol-60', ['Algol-60', 'Fortran', 'Simula', 'C', 'Pascal'], acertada).

