:- dynamic pergunta_missao/6.

pergunta_missao('M2_Q2', 0, 'Qual das seguintes é uma característica das linguagens de alto nível?', 'Sintaxe mais estruturada e independente da arquitetura do computador.', ['Sintaxe mais estruturada e independente da arquitetura do computador.', 'Baixa portabilidade.', 'Dificuldade de implementação.', 'Instruções que refletem diretamente as operações da máquina.', 'Pouca expressividade.'], nao_acertada).
pergunta_missao('M2_Q8', 0, 'Qual das linguagens a seguir é citada como um exemplo de LP compilada estaticamente?', 'C++', ['Python', 'Java', 'PHP', 'C#', 'C++'], nao_acertada).
pergunta_missao('M2_Q9', 0, 'De acordo com o diagrama de paradigmas, quais são as duas grandes categorias de paradigmas?', 'Imperativo e Declarativo.', ['Estruturado e Orientado a objetos.', 'Funcional e Lógico.', 'Imperativo e Declarativo.', 'Concorrente e Estruturado.', 'Imperativo e Funcional.'], nao_acertada).
pergunta_missao('M2_Q11', 0, 'Qual das linguagens é um exemplo de paradigma puramente lógico?', 'Prolog', ['Lisp', 'C++', 'Java', 'Python', 'Prolog'], nao_acertada).
pergunta_missao('M2_Q12', 0, 'Que paradigma de LP é definido por \'objeto, mensagem\'?', 'Paradigma orientado a objetos.', ['Paradigma funcional.', 'Paradigma orientado a objetos.', 'Paradigma lógico.', 'Paradigma concorrente.', 'Paradigma imperativo.'], nao_acertada).
pergunta_missao('M2_Q13', 0, 'Qual é a principal desvantagem de linguagens interpretadas?', 'Ineficiência e maior consumo de memória.', ['Problemas com portabilidade.', 'Dificuldade para prototipação.', 'Ineficiência e maior consumo de memória.', 'Sintaxe complexa.', 'Falta de flexibilidade.'], nao_acertada).
pergunta_missao('M2_Q14', 0, 'Qual das linguagens a seguir é um exemplo de LP interpretada?', 'Java.', ['Java.', 'C.', 'Fortran.', 'Pascal.', 'Assembly.'], nao_acertada).
pergunta_missao('M2_Q15', 0, 'A qual fase da compilação se refere a transformação de caracteres em tokens?', 'Análise léxica.', ['Análise sintática.', 'Análise semântica.', 'Tradução para linguagem de montagem.', 'Análise léxica.', 'Tradução para linguagem intermediária.'], nao_acertada).
pergunta_missao('M2_Q16', 0, 'De acordo com o documento, o que é a sintaxe de um programa?', 'O formato do programa e como suas construções devem ser arranjadas.', ['O significado do programa.', 'O formato do programa e como suas construções devem ser arranjadas.', 'A sua eficiência.', 'A sua capacidade de ser interpretado.', 'A sua universalidade.'], nao_acertada).
pergunta_missao('M2_Q17', 0, 'Qual é a definição do paradigma funcional?', 'Função, aplicação, avaliação.', ['Relação, dedução.', 'Estado, atribuição, sequência.', 'Objeto, mensagem.', 'Processo, comunicação.', 'Função, aplicação, avaliação.'], nao_acertada).
pergunta_missao('M2_Q18', 0, 'Um programa sintaticamente correto é sempre semanticamente correto?', 'Não, pois podem ocorrer erros de significado.', ['Sim, sempre.', 'Sim, se for compilado.', 'Sim, se for interpretado.', 'Não, pois podem ocorrer erros de significado.', 'Sim, desde que não tenha erros de digitação.'], nao_acertada).
pergunta_missao('M2_Q19', 0, 'Qual das seguintes é uma forma de apresentar a semântica de uma linguagem?', 'Semântica Axiomática.', ['Sintaxe de Backus Naur (BNF).', 'Fase de análise léxica.', 'Semântica Axiomática.', 'Análise sintática.', 'Fase de tradução.'], nao_acertada).
pergunta_missao('M2_Q20', 0, 'Qual das linguagens a seguir é classificada como multiparadigma por combinar funcional e OO?', 'Ocaml', ['Java', 'C++', 'Ada', 'Ocaml', 'Prolog'], nao_acertada).
pergunta_missao('M2_Q1', 0, 'O que é uma linguagem de baixo nível segundo o documento?', 'Uma linguagem cujas instruções são escritas utilizando as instruções do microprocessador.', ['Uma linguagem que não precisa de compilador.', 'Uma linguagem com sintaxe complexa e difícil de usar.', 'Uma linguagem cujas instruções são escritas utilizando as instruções do microprocessador.', 'Uma linguagem que suporta vários paradigmas.', 'Uma linguagem que não é universal.'], acertada).
pergunta_missao('M2_Q3', 0, 'Qual o principal problema das linguagens compiladas mencionado no texto?', 'Problemas com portabilidade e depuração.', ['Baixa eficiência.', 'Problemas com portabilidade e depuração.', 'Lentidão na execução.', 'Maior consumo de memória.', 'Sintaxe muito complexa.'], acertada).
pergunta_missao('M2_Q4', 0, 'De acordo com o documento, qual o papel de um compilador?', 'Traduzir um programa de uma linguagem para outra semanticamente equivalente.', ['Executar o programa diretamente.', 'Converter a linguagem de máquina em código fonte.', 'Apenas verificar erros de sintaxe.', 'Traduzir um programa de uma linguagem para outra semanticamente equivalente.', 'Tornar o programa mais eficiente.'], acertada).
pergunta_missao('M2_Q5', 0, 'Qual das seguintes é uma vantagem das linguagens interpretadas?', 'Flexibilidade, portabilidade e facilidade para prototipação.', ['Maior eficiência.', 'Flexibilidade, portabilidade e facilidade para prototipação.', 'Menor consumo de memória.', 'Tradução direta para código de máquina.', 'Sintaxe mais simples.'], acertada).
pergunta_missao('M2_Q6', 0, 'Qual é a primeira fase da compilação de acordo com o exemplo?', 'Análise Léxica.', ['Tradução para linguagem de montagem.', 'Análise Semântica.', 'Análise Sintática.', 'Tradução para linguagem intermediária.', 'Análise Léxica.'], acertada).
pergunta_missao('M2_Q7', 0, 'O que é \'semântica\' de um programa?', 'O significado do programa.', ['O significado do programa.', 'O formato do programa.', 'A sua capacidade de ser compilado.', 'O uso de variáveis mutáveis.', 'O número de linhas de código.'], acertada).
pergunta_missao('M2_Q10', 0, 'Qual dos paradigmas listados a seguir é uma subcategoria do paradigma Imperativo?', 'Estruturado.', ['Estruturado.', 'Lógico.', 'Funcional.', 'Concorrente.', 'Orientado a objetos.'], acertada).

