:- dynamic pergunta_missao/6.

pergunta_missao('M1_Q6', 0, 'Qual linguagem de programação é citada como exemplo de uma LP de baixo nível?', 'Assembly', ['Python', 'Java', 'C++', 'Assembly', 'Pascal'], nao_acertada).
pergunta_missao('M1_Q7', 0, 'Qual das seguintes linguagens é descrita como sendo a primeira a introduzir conceitos de orientação a objetos (OO) como classe e herança?', 'Simula', ['Pascal', 'Fortran', 'C', 'Simula', 'Lisp'], nao_acertada).
pergunta_missao('M1_Q8', 0, 'Qual LP desenvolvida pela IBM na década de 1950 foi voltada para computação numérica e científica e introduziu o conceito de arrays e procedimentos com parâmetros?', 'Fortran', ['Algol-60', 'Pascal', 'C', 'Simula', 'Fortran'], nao_acertada).
pergunta_missao('M1_Q9', 0, 'Qual LP descrita no documento como a primeira puramente orientada a objetos e dinamicamente tipada e oferece suporte a reflexão?', 'Smalltalk', ['Java', 'C', 'C++', 'Smalltalk', 'Simula'], nao_acertada).
pergunta_missao('M1_Q11', 0, 'Qual linguagem foi fortemente inspirada em Algol e se tornou a principal para ensino de programação por sua simplicidade e suporte a programação estruturada?', 'Pascal', ['Pascal', 'C', 'Simula', 'Fortran', 'Lisp'], nao_acertada).
pergunta_missao('M1_Q13', 0, 'Qual linguagem de grande importância histórica foi utilizada para reimplementar o sistema operacional Unix?', 'C', ['C', 'Java', 'Python', 'Fortran', 'Lisp'], nao_acertada).
pergunta_missao('M1_Q14', 0, 'A que estilo de programação a linguagem Lisp de 1958 é precursora?', 'Programação funcional', ['Programação orientada a objetos', 'Programação funcional', 'Programação imperativa', 'Programação estruturada', 'Programação lógica'], nao_acertada).
pergunta_missao('M1_Q16', 0, 'Qual é o significado da sigla COBOL?', 'Common Business Oriented Language', ['Common Object-Based Online Language', 'Common Business Oriented Language', 'Common Business and Office Language', 'Computer Business Oriented Language', 'Common Block-Oriented Language'], nao_acertada).
pergunta_missao('M1_Q17', 0, 'A qual das seguintes LP o documento se refere como \'Linguagem de Programação em Lógica\'?', 'Prolog', ['Lisp', 'Java', 'Python', 'Prolog', 'Smalltalk'], nao_acertada).
pergunta_missao('M1_Q18', 0, 'Qual das seguintes características de uma LP está relacionada à execução em um tempo aceitável para os propósitos de uso da linguagem?', 'Eficiência', ['Eficiência', 'Simplicidade', 'Universalidade', 'Expressividade', 'Implementável'], nao_acertada).
pergunta_missao('M1_Q19', 0, 'Segundo o documento, até os anos 50, quais eram os principais usos dos computadores?', 'Cálculos numéricos.', ['Aplicações de IA.', 'Sistemas de informação comerciais.', 'Cálculos numéricos.', 'Edição de texto.', 'Jogos.'], nao_acertada).
pergunta_missao('M1_Q20', 0, 'Qual das opções abaixo não é uma das características desejáveis em uma LP conforme listado no slide \'Características\' e \'Simplicidade\'?', 'Maior poder expressivo que dificulta o aprendizado.', ['Expressividade.', 'Simplicidade.', 'Suporte a abstração.', 'Implementável.', 'Maior poder expressivo que dificulta o aprendizado.'], nao_acertada).
pergunta_missao('M1_Q10', 0, 'O documento menciona que a programação estruturada começou a ser introduzida com qual linguagem?', 'Algol-60', ['Algol-60', 'Fortran', 'Simula', 'C', 'Pascal'], acertada).
pergunta_missao('M1_Q12', 0, 'Qual linguagem projetada para sistemas de informação comerciais é descrita como verborrágica e ainda hoje é ativa?', 'Cobol', ['Java', 'Pascal', 'Cobol', 'Fortran', 'Python'], acertada).
pergunta_missao('M1_Q15', 0, 'O que a linguagem Algol-60 introduziu para melhorar a legibilidade e o tempo de desenvolvimento de programas?', 'O uso de blocos delimitados de código e escopo.', ['O uso de desvios incondicionais.', 'O uso de linguagens de baixo nível.', 'O uso de blocos delimitados de código e escopo.', 'A introdução da programação puramente orientada a objetos.', 'A ênfase na computação numérica.'], acertada).

